#!/usr/bin/env node
import { nextTick } from 'node:process';

(() => {
  process.setSourceMapsEnabled(true);
  process.title = 'node-icon-font'

  process.setUncaughtExceptionCaptureCallback(error => {
    console.log(error);
    process.exit(1);
  });


  nextTick(() => {
    import('./lib/index.js');
  });
})();